services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.1
    restart: unless-stopped
    user: "1035"
    env_file:
      - ./env
    volumes:
      - ./conf:/usr/share/grafana/conf:rw
      - ./data:/var/lib/grafana:rw
    command:
      - --config=/usr/share/grafana/conf/custom.ini
    ports:
      - 3000:3000
    network_mode: host
