global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["10.0.10.11:9090"]
        labels:
          device_name: "Prometheus_DS923"

  - job_name: "loki"
    static_configs:
      - targets: ["10.0.10.11:3100"]
        labels:
          device_name: "Loki_DS923"

  - job_name: "grafana"
    static_configs:
      - targets: ["10.0.10.11:3000"]
        labels:
          device_name: "Grafana_DS923"

  - job_name: "Omada"
    static_configs:
      - targets: ["10.0.10.11:51772"]
        labels:
          device_name: "Omada_DS923"
    metrics_path: /metrics

  - job_name: "TF_Backend"
    static_configs:
      - targets: ["10.0.10.11:8001"]
        labels:
          device_name: "TF_Backend_DS923"
    metrics_path: /metrics

  - job_name: "Synology"
    static_configs:
      - targets: ["10.0.10.11:9116"]
    metrics_path: /snmp
    params:
      module: [synology]
      auth: [dsm_snmp3]
      target: ["10.0.10.11"]

  - job_name: "Ohm"
    static_configs:
      - targets: ["10.0.10.21:4445"]
        labels:
          device_name: "LianLi"

  - job_name: "Vault"
    static_configs:
      - targets: ["10.0.10.11:8200"]
    metrics_path: /v1/sys/metrics
    params:
      format: [prometheus]

  - job_name: "pve"
    static_configs:
      - targets:
          - 10.0.10.105 # pve-i5.
          - 10.0.10.107 # pve-r7.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ["1"]
      node: ["1"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.10.10:9221 # PVE exporter.

