services:
  tf-backend:
    container_name: tf-backend
    image: docker-hub.horna.local/terraform_http_backend:latest
    environment:
      - LOKI_URL=http://10.0.10.11:3100
      - LOG_LEVEL=info
    volumes:
      - ./states:/root/states
    ports:
      - 8001:8080