services:
  vault:
    image: hashicorp/vault:1.20
    container_name: vault
    command: vault server -config=/vault/config/local.json
    environment:
      VAULT_UI: true
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": true,
                "telemetry": {
                  "unauthenticated_metrics_access": true
                }
              }
            }
          ],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "7200h",
          "ui": true,
          "api_addr": "https://vault.horna.local"
        }
    restart: unless-stopped
    volumes:
      - vault-file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    network_mode: host

volumes:
  vault-file:
    driver: local
    driver_opts:
      type: none
      device: ./file
      o: bind