auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-06-17
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: tsdb_index_
        period: 24h

limits_config:
  retention_period: 365d
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_streams_per_user: 5000
  max_entries_limit_per_query: 10000
  max_query_parallelism: 32
  max_query_series: 50000

compactor:
  working_directory: /tmp/loki/retention
  retention_enabled: true
  retention_delete_delay: 24h
  delete_request_store: filesystem

analytics:
  reporting_enabled: false