services:
  Prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    restart: unless-stopped
    user: "1036"
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ./conf:/etc/prometheus:rw
      - ./data:/prometheus:rw
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2y
      - --storage.tsdb.path=/prometheus
    ports:
      - 9090:9090
    network_mode: host
